"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from django.core.exceptions import ImproperlyConfigured
from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_ROOT = BASE_DIR.parent
load_dotenv(PROJECT_ROOT / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name: str, default=None):
    value = os.getenv(name)
    if value is None:
        return list(default or [])
    return [item.strip() for item in value.split(",") if item.strip()]


def env_required(name: str, *, default=None, required: bool = False) -> str:
    value = os.getenv(name, default)
    if required and (value is None or not str(value).strip()):
        raise ImproperlyConfigured(f"Environment variable {name} is required.")
    return value

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
IS_TEST = "test" in sys.argv
DJANGO_ENV = os.getenv("DJANGO_ENV", "test" if IS_TEST else "development").strip().lower()
if DJANGO_ENV == "prod":
    DJANGO_ENV = "production"

DEBUG = env_bool("DJANGO_DEBUG", default=DJANGO_ENV != "production")
IS_PRODUCTION = DJANGO_ENV == "production"

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_required(
    "DJANGO_SECRET_KEY",
    default=None if IS_PRODUCTION else "django-insecure-local-dev-key",
    required=IS_PRODUCTION,
)

if DEBUG:
    ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", default=["localhost", "127.0.0.1", "[::1]"])
else:
    ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS")
    if not ALLOWED_HOSTS:
        raise ImproperlyConfigured("DJANGO_ALLOWED_HOSTS must be set when DEBUG is disabled.")

FRONTEND_URL = env_required(
    "FRONTEND_URL",
    default=None if IS_PRODUCTION else "http://localhost:5173",
    required=IS_PRODUCTION,
)

CSRF_TRUSTED_ORIGINS = env_list("DJANGO_CSRF_TRUSTED_ORIGINS", default=[FRONTEND_URL] if IS_PRODUCTION else [])

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'users.apps.UsersConfig',
    'rest_framework_simplejwt.token_blacklist',
    'trips',
    'expenses',
    'django_rest_passwordreset',
    'payments',
    'notifications',
    'checklists',
    'itinerary'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env_required("DJANGO_DB_NAME", default=None if IS_PRODUCTION else "equaltrip_db", required=IS_PRODUCTION),
        'USER': env_required("DJANGO_DB_USER", default=None if IS_PRODUCTION else "trip_user", required=IS_PRODUCTION),
        'PASSWORD': env_required("DJANGO_DB_PASSWORD", default=None if IS_PRODUCTION else "trip_password", required=IS_PRODUCTION),
        'HOST': env_required("DJANGO_DB_HOST", default=None if IS_PRODUCTION else "localhost", required=IS_PRODUCTION),
        'PORT': env_required("DJANGO_DB_PORT", default=None if IS_PRODUCTION else "5432", required=IS_PRODUCTION),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_HEADERS = (*default_headers, 'x-client-timezone')
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [FRONTEND_URL]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

AUTH_USER_MODEL = 'users.User'

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
IMAGE_UPLOAD_MAX_BYTES = int(os.getenv("IMAGE_UPLOAD_MAX_BYTES", str(5 * 1024 * 1024)))
DOCUMENT_UPLOAD_MAX_BYTES = int(os.getenv("DOCUMENT_UPLOAD_MAX_BYTES", str(10 * 1024 * 1024)))

OPENEXCHANGERATES_API_KEY = env_required(
    "OPENEXCHANGERATES_API_KEY",
    default=None if IS_PRODUCTION else "",
    required=IS_PRODUCTION,
)
FX_RATES_ASYNC = env_bool("FX_RATES_ASYNC", default=not IS_TEST)
FX_RATE_FETCH_MAX_WORKERS = int(os.getenv("FX_RATE_FETCH_MAX_WORKERS", "1"))
FX_RATE_FETCH_LOCK_SECONDS = int(os.getenv("FX_RATE_FETCH_LOCK_SECONDS", "60"))
FX_RATE_FETCH_TIMEOUT = int(os.getenv("FX_RATE_FETCH_TIMEOUT", "10"))

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER = os.getenv("YANDEX_SMTP_USER")
DEFAULT_FROM_EMAIL = os.getenv("YANDEX_SMTP_FROM") or EMAIL_HOST_USER
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_PASSWORD = os.getenv("YANDEX_SMTP_PASSWORD")
EMAIL_TIMEOUT = 15  # секунды
EMAIL_NOTIFICATIONS_ASYNC = env_bool("EMAIL_NOTIFICATIONS_ASYNC", default=not IS_TEST)
EMAIL_NOTIFICATION_MAX_WORKERS = int(os.getenv("EMAIL_NOTIFICATION_MAX_WORKERS", "2"))
