"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import sys
from corsheaders.defaults import default_headers
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "django-insecure-vv9cs9-+b*bx9is&%0u2j7m=7m5i=!jd%37lrvey5#74(fc0&+")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "1").strip().lower() in {"1", "true", "yes", "on"}

if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = [host.strip() for host in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if host.strip()]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',
    'users.apps.UsersConfig',
    'rest_framework_simplejwt.token_blacklist',
    'trips',
    'expenses',
    'django_rest_passwordreset',
    'payments',
    'notifications',
    'checklists',
    'itinerary'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv("DJANGO_DB_NAME", "equaltrip_db"),
        'USER': os.getenv("DJANGO_DB_USER", "trip_user"),
        'PASSWORD': os.getenv("DJANGO_DB_PASSWORD", "trip_password"),
        'HOST': os.getenv("DJANGO_DB_HOST", "localhost"),
        'PORT': os.getenv("DJANGO_DB_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = (*default_headers, 'x-client-timezone')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

AUTH_USER_MODEL = 'users.User'

FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:5173")

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"
IMAGE_UPLOAD_MAX_BYTES = int(os.getenv("IMAGE_UPLOAD_MAX_BYTES", str(5 * 1024 * 1024)))
DOCUMENT_UPLOAD_MAX_BYTES = int(os.getenv("DOCUMENT_UPLOAD_MAX_BYTES", str(10 * 1024 * 1024)))

OPENEXCHANGERATES_API_KEY = os.getenv("OPENEXCHANGERATES_API_KEY", "e3888ae5b7854938a4367005549bedc7")
FX_RATES_ASYNC = os.getenv("FX_RATES_ASYNC", "0" if "test" in sys.argv else "1").strip().lower() in {"1", "true", "yes", "on"}
FX_RATE_FETCH_MAX_WORKERS = int(os.getenv("FX_RATE_FETCH_MAX_WORKERS", "1"))
FX_RATE_FETCH_LOCK_SECONDS = int(os.getenv("FX_RATE_FETCH_LOCK_SECONDS", "60"))
FX_RATE_FETCH_TIMEOUT = int(os.getenv("FX_RATE_FETCH_TIMEOUT", "10"))

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER = os.getenv("YANDEX_SMTP_USER")
DEFAULT_FROM_EMAIL = os.getenv("YANDEX_SMTP_FROM") or EMAIL_HOST_USER
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False
EMAIL_HOST_PASSWORD = os.getenv("YANDEX_SMTP_PASSWORD")
EMAIL_TIMEOUT = 15  # секунды
EMAIL_NOTIFICATIONS_ASYNC = os.getenv("EMAIL_NOTIFICATIONS_ASYNC", "0" if "test" in sys.argv else "1").strip().lower() in {"1", "true", "yes", "on"}
EMAIL_NOTIFICATION_MAX_WORKERS = int(os.getenv("EMAIL_NOTIFICATION_MAX_WORKERS", "2"))
