# Generated by Django 5.2.9 on 2026-05-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checklists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checklist',
            options={'verbose_name': 'Чек-лист', 'verbose_name_plural': 'Чек-листы'},
        ),
        migrations.AlterModelOptions(
            name='checklistcomment',
            options={'verbose_name': 'Комментарий к задаче', 'verbose_name_plural': 'Комментарии к задачам'},
        ),
        migrations.AlterModelOptions(
            name='checklistitem',
            options={'verbose_name': 'Задача чек-листа', 'verbose_name_plural': 'Задачи чек-листа'},
        ),
    ]
