# Generated by Django 5.2.9 on 2026-05-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayplan',
            options={'ordering': ('date',), 'verbose_name': 'План дня', 'verbose_name_plural': 'Планы по дням'},
        ),
        migrations.AlterModelOptions(
            name='dayplancomment',
            options={'verbose_name': 'Комментарий к активности', 'verbose_name_plural': 'Комментарии к активностям'},
        ),
        migrations.AlterModelOptions(
            name='dayplanitem',
            options={'verbose_name': 'Активность', 'verbose_name_plural': 'Активности'},
        ),
    ]
