# Generated by Django 5.2.9 on 2026-05-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'verbose_name': 'Поездка', 'verbose_name_plural': 'Поездки'},
        ),
        migrations.AlterModelOptions(
            name='tripinvite',
            options={'verbose_name': 'Приглашение', 'verbose_name_plural': 'Приглашения'},
        ),
        migrations.AlterModelOptions(
            name='tripmember',
            options={'verbose_name': 'Участник поездки', 'verbose_name_plural': 'Участники поездки'},
        ),
    ]
