# Generated by Django 5.2.9 on 2026-01-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='amount_rub',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='fx_rate',
            field=models.DecimalField(decimal_places=6, default=1, max_digits=12),
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('rate_to_rub', models.DecimalField(decimal_places=6, max_digits=12)),
            ],
            options={
                'indexes': [models.Index(fields=['currency', 'date'], name='expenses_ex_currenc_d0811d_idx')],
                'unique_together': {('currency', 'date')},
            },
        ),
    ]
