# Generated by Django 5.2.9 on 2026-05-02 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0004_expense_amount_rub_expense_fx_rate_exchangerate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="receipt",
            field=models.FileField(blank=True, null=True, upload_to="receipts/"),
        ),
    ]
