# Generated by Django 5.2.9 on 2026-05-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_alter_expense_receipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="amount_rub",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=30),
        ),
        migrations.AlterField(
            model_name="expense",
            name="fx_rate",
            field=models.DecimalField(decimal_places=12, default=1, max_digits=24),
        ),
        migrations.AlterField(
            model_name="exchangerate",
            name="rate_to_rub",
            field=models.DecimalField(decimal_places=12, max_digits=24),
        ),
    ]
