# Generated by Django 5.2.9 on 2026-05-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_expand_fx_precision"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="spent_time_known",
            field=models.BooleanField(default=True),
        ),
    ]
