# Generated by Django 5.2.9 on 2026-05-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_expense_spent_date_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerate',
            options={'verbose_name': 'Курс валюты', 'verbose_name_plural': 'Курсы валют'},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'verbose_name': 'Расход', 'verbose_name_plural': 'Расходы'},
        ),
        migrations.AlterModelOptions(
            name='expensecategory',
            options={'verbose_name': 'Категория расхода', 'verbose_name_plural': 'Категории расходов'},
        ),
        migrations.AlterModelOptions(
            name='expenseshare',
            options={'verbose_name': 'Доля расхода', 'verbose_name_plural': 'Доли расходов'},
        ),
    ]
