# Generated by Django 5.2.9 on 2026-05-15 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settlement',
            options={'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
    ]
